### ISSUE TITLE
Old messages stuck on "trying to send"

### ISSUE THREAD

**Issue by dyoung522** [yuya-oc/electron-mattermost#20]
When attempting to leave a message while not connected to the network, those messages go into a permanent "sending" state without any way to remove them.

Illustration here: ![rending forever](https://dl.dropboxusercontent.com/s/5zflghgyfzyc4ga/2016-01-22%20at%2010.11%20AM.png)

That bottom message was sent while off the network (unknowingly by me at the time), but now I cannot get rid of it. Any new messages get sent immediately as expected.

**Comment by yuya-oc** [comment]
Does that appear after restarting app? If so, please try `Shift+Ctrl(Command)+R`.

**Comment by dyoung522** [comment]
Yes, the phantom messages remain in a perpetual "sending" state even after multiple restarts and cache clears. Even a after a full system reboot, they remain.

**Comment by yuya-oc** [comment]
Could you try following? If the problem is not resolved, I can't come up with solution anymore.

1. Please remove related directory contents excluding `config.json` after quitting the app. Then please try using.
  * Windows: `%USERPROFILE%\AppData\Roaming\electron-mattermost/`
  * OS X: `~/Library/Application Support/electron-mattermost/`
  * Linux: `~/.config/electron-mattermost/`
2. Please check whether it happens on web browsers.
  * If it happened on browsers, it might be a issue for Mattermost.

**Comment by dyoung522** [comment]
Yes, removing everything (except `config.json`) in the `~/Library/Application Support/electron-mattermost` directory succeeded in removing those messages.

**Comment by dyoung522** [comment]
As for your second question, I have not seen this behavior in the browser.

**Comment by yuya-oc** [comment]
Thank you for feedback. I think the directory is mainly managed for browser behavior. Possibly the issue happens also on web browsers.
