### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by smackjack3** [yuya-oc/electron-mattermost#7]
After upgrading to Mattermost 1.3.0 I've been experiencing formatting issues with this app.  The elements for the username and timestamp for every post are showing up as ul > li elements and comments to existing posts are not being abbreviated correctly.

I've overwritten the 0.4 version of the app with the 1.0 version but the issue persists.  I do not have this issue when accessing in the browser.

![image](https://cloud.githubusercontent.com/assets/6363743/12127734/df5eb744-b3c6-11e5-8261-4bf7b43ea369.png)

**Comment by yuya-oc** [comment]
It might be caused by browser cache. For now, could you try removing caches?
If you use Windows, cache directory exists under `%HOME%\AppData\Roaming\electron-mattermost`.
Please check `appData` and `userData` of `app.getPath()` for other OS.
http://electron.atom.io/docs/v0.36.0/api/app/#app-getpath-name

**Comment by smackjack3** [comment]
Sorry I'm on a Mac and not familiar with Electron.  How would I make that API call?

**Comment by yuya-oc** [comment]
v1.0.1 has a new feature, "Clear Cache and Reload". It's helpful in such a this case.

**Comment by smackjack3** [comment]
That's awesome - very helpful for my less technically-inclined colleagues.

Thank you!
