### ISSUE TITLE
Badges don't disappear when clicking on the chat

### ISSUE THREAD

**Issue by stefuNz** [yuya-oc/electron-mattermost#9]
Hi,

the badges in the Mac OS X dock (didn't try windows) don't disappear when i click on the chat which has new messages, only when i leave this chat (switch to another room)

**Comment by stefuNz** [comment]
Same goes for windows as my colleague has tested it just now.

**Comment by yuya-oc** [comment]
It's a side effect of solution for #2. As you said, badges disappear by switching to another channel.

I think v1.0.1 behavior is better than '<=v1.0.0'. Because it has been important that "Are there new messages while I 'm away from the PC?" in my daily work. 

If you have any idea for this, please let me know. Of course PR is welcome.

**Comment by Johnich** [comment]
Same issue here. This 'fake unread message' makes my teammates throw out lots of complaints. Hope it will be rolled back in next version.

**Comment by yuya-oc** [comment]
The fix is WIP at #22. For now, I think you can overwrite `src/browser/webview/mattermost.js` of v1.0.2 with v1.0.0 version (I can't test it now).

**Comment by yuya-oc** [comment]
v1.0.3 clears badges for active channel when the tab(or window) is focused.

**Comment by jobspierings** [comment]
@yuya-oc this fix works great on OS X.
